namespace GameEngine.Domain.Model;

public sealed record OutcomeAuthorityReadinessMarkers(
    bool GameManifestSchemaReady,
    bool AuthorityCertificateChainReady,
    bool OutcomeDslReady,
    bool MathRtpGovernanceReady,
    bool RngProviderGovernanceReady,
    bool OutcomeDryRunPipelineReady,
    bool MathEvaluationDryRunReady,
    bool CertificationPackReady,
    bool CertificateSigningFrameworkReady,
    bool StatisticalValidationReady,
    bool OperationalControlsReady,
    bool OutcomeProviderRuntimeReady = true,
    bool OutcomeRuntimeIdempotencyReady = true,
    bool OutcomeRuntimeAdvisoryLockingReady = true);

public sealed record OutcomeAuthorityActivationRequest(
    OutcomeAuthorityReadinessMarkers ReadinessMarkers,
    bool ProductionOutcomeAuthorityEnabled,
    bool ProductionRngProviderEligible,
    bool SigningProviderProductionEligible,
    bool CertificationPackReady,
    bool UsesSimulationOrTestProvider,
    bool JurisdictionOmitted,
    bool ManifestRequiresCertification,
    bool CertificationOmitted,
    bool HasFailedOrInconclusiveStatisticalValidation,
    bool HasActiveEmergencyDisable,
    bool HasExactOutcomeProviderBinding = true,
    bool OutcomeProviderActiveAndEligible = true,
    bool OutcomeProviderCapabilitiesSatisfied = true,
    bool SilentFallbackConfigured = false,
    bool UsesSimulationOrTestOutcomeProvider = false,
    bool CertifiedCsprngProviderRequirementsSatisfied = true,
    bool EntropyProviderProductionEligible = true,
    bool DrbgHealthEvidenceSatisfied = true,
    bool UnbiasedSamplingCapabilitiesSatisfied = true,
    bool NoRawSecretMaterialPersisted = true,
    bool ProvablyFairProviderRequirementsSatisfied = true,
    bool ProvablyFairCommitAlgorithmDefined = true,
    bool ProvablyFairVerificationAlgorithmDefined = true,
    bool ProvablyFairReceiptSupportAvailable = true,
    bool ProvablyFairNoncePolicyValid = true,
    bool ProvablyFairCommitmentPolicyValid = true,
    bool ProvablyFairNoSeedLeakage = true,
    bool OutcomeProviderRuntimeReady = true,
    bool OutcomeRuntimeIdempotencyConfigured = true,
    bool OutcomeRuntimeAdvisoryLockingConfigured = true,
    bool ProductionOutcomeGenerationDisabled = true);

public sealed record OutcomeAuthorityActivationGuardrailResult(
    bool Allowed,
    IReadOnlyCollection<string> Blockers,
    IReadOnlyCollection<string> Warnings);
