namespace GameEngine.Domain.Model;

public sealed record SettlementInput(
    Guid SettlementInputId,
    Guid MathEvaluationCertificateId,
    string MathEvaluationCertificateHash,
    Guid OutcomeCertificateId,
    string OutcomeCertificateHash,
    string TicketReference,
    string GameManifestId,
    string GameManifestVersion,
    string GameManifestHash,
    string MathModelId,
    string MathModelVersion,
    string MathModelHash,
    string PaytableId,
    string PaytableVersion,
    string PaytableHash,
    string EvaluatorVersion,
    PrizeOutcome EvaluationOutcome,
    string PrizeTier,
    PrizeFacts PrizeFacts,
    string PrizeFactsHash,
    decimal PayoutUnits,
    decimal Multiplier,
    string ReplayHash,
    string IdempotencyKey,
    DateTimeOffset IssuedAt,
    IReadOnlyDictionary<string, object?> Provenance,
    string CanonicalPayloadJson,
    string CanonicalPayloadHash);
