namespace GameEngine.Domain.Model;

public sealed record SettlementInput(
    Guid SettlementInputId,
    Guid MathEvaluationCertificateId,
    string MathEvaluationCertificateHash,
    Guid OutcomeCertificateId,
    string OutcomeCertificateHash,
    string TicketReference,
    string GameManifestId,
    string GameManifestVersion,
    string GameManifestHash,
    string MathModelId,
    string MathModelVersion,
    string MathModelHash,
    string PaytableId,
    string PaytableVersion,
    string PaytableHash,
    string EvaluatorVersion,
    PrizeOutcome EvaluationOutcome,
    string PrizeTier,
    PrizeFacts PrizeFacts,
    string PrizeFactsHash,
    decimal PayoutUnits,
    decimal Multiplier,
    string ReplayHash,
    string IdempotencyKey,
    DateTimeOffset IssuedAt,
    IReadOnlyDictionary<string, object?> Provenance,
    string CanonicalPayloadJson,
    string CanonicalPayloadHash,
    string InputKind = "ITEM");

public sealed record TicketDrawSettlementItemEvidence(
    Guid TicketItemId,
    int ItemIndex,
    long StakeMinor,
    Guid MathEvaluationId,
    Guid MathEvaluationCertificateId,
    string MathEvaluationCertificateHash,
    PrizeOutcome EvaluationOutcome,
    string PrizeTier,
    long GrossReturnMinor,
    long RefundReturnMinor,
    long LossStakeMinor,
    string PrizeFactsHash);

public sealed record TicketDrawSettlementAggregateEvidence(
    Guid SettlementInputId,
    Guid TicketId,
    Guid DrawId,
    Guid ProductVersionId,
    string ProductVersionHash,
    string Currency,
    long TotalReservedStakeMinor,
    long PreCapGrossReturnMinor,
    long? EffectiveCapMinor,
    string CapScope,
    long PostCapGrossReturnMinor,
    long CaptureAmountMinor,
    long ReleaseAmountMinor,
    long CreditAmountMinor,
    string ItemEvidenceHash,
    string CanonicalAggregateHash,
    IReadOnlyList<TicketDrawSettlementItemEvidence> Items);
