export function parseAvailableSpots(value: string) {
  return value
    .split(",")
    .map((spot) => Number(spot.trim()))
    .filter((spot) => Number.isFinite(spot) && spot > 0);
}

export function getGameLocalId(game: any, index: number) {
  return (
    game.externalId ||
    `${game.state || ""}-${game.name || ""}-${index}`
      .toUpperCase()
      .replace(/[^A-Z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
  );
}

export function buildGamePayload(form: any) {
  const isKenoGame = form.gameType === "keno_style";

  if (isKenoGame) {
    const numberRangeMin = Number(form.numberRangeMin || 0);
    const numberRangeMax = Number(form.numberRangeMax || 0);
    const numbersDrawn = Number(form.numbersDrawn || 0);
    const availableSpots = parseAvailableSpots(String(form.availableSpots || ""));
    const drawIntervalSeconds = Number(form.drawIntervalSeconds || 0);
    const drawIdPrefix = String(form.drawIdPrefix || "").trim();

    if (
      numberRangeMin <= 0 ||
      numberRangeMax <= 0 ||
      numberRangeMin >= numberRangeMax ||
      numbersDrawn <= 0 ||
      numbersDrawn > numberRangeMax - numberRangeMin + 1 ||
      availableSpots.length === 0 ||
      drawIntervalSeconds <= 0 ||
      drawIdPrefix === ""
    ) {
      return {
        ok: false,
        message:
          "Please enter a valid Keno range, draw count, spot levels, draw interval, and draw ID prefix.",
        payload: null,
      };
    }

    return {
      ok: true,
      message: "",
      payload: {
        ...form,
        state: "",
        gameFamily: "keno",
        requiresPaytable: true,
        activePaytableId: form.activePaytableId || null,
        payoutMultiplier: "",
        numberRangeMin: String(numberRangeMin),
        numberRangeMax: String(numberRangeMax),
        numbersDrawn: String(numbersDrawn),
        availableSpots,
        bullseyeEnabled: Boolean(form.bullseyeEnabled),
        drawFrequencyType: "recurring",
        drawIntervalSeconds,
        drawIdPrefix,
        autoGenerateDraws: Boolean(form.autoGenerateDraws),
        scheduleType: null,
        recurringFrequency: null,
        defaultDrawTime: "",
        defaultCutoffTime: "",
        numberPoolMin: String(numberRangeMin),
        numberPoolMax: String(numberRangeMax),
        drawCount: String(numbersDrawn),
        allowedSpotCounts: availableSpots,
      },
    };
  }

  if (
    !form.state ||
    !form.mainNumbersCount ||
    !form.mainNumbersMin ||
    !form.mainNumbersMax ||
    !form.payoutMultiplier
  ) {
    return {
      ok: false,
      message:
        "Please enter the lottery state, main number count, range, and payout multiplier.",
      payload: null,
    };
  }

  return {
    ok: true,
    message: "",
    payload: {
      ...form,
      gameFamily: "lottery",
      requiresPaytable: false,
      activePaytableId: null,
      drawFrequencyType: "manual",
      drawIntervalSeconds: null,
      drawIdPrefix: null,
      autoGenerateDraws: false,
    },
  };
}
