export const IDENTITY_CLASSES = {
  PLATFORM_OPERATOR: "PLATFORM_OPERATOR",
  HIERARCHY_PARTICIPANT: "HIERARCHY_PARTICIPANT",
  PLAYER: "PLAYER",
  SYSTEM_SERVICE: "SYSTEM_SERVICE",
} as const;

export const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  DISABLED: "DISABLED",
  PENDING_ACTIVATION: "PENDING_ACTIVATION",
} as const;

export const AUTHENTICATION_EVENT_TYPES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED: "ACCOUNT_UNLOCKED",
  LOGOUT: "LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_REQUEST_IGNORED: "PASSWORD_RESET_REQUEST_IGNORED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  API_CLIENT_CREATED: "API_CLIENT_CREATED",
  API_TOKEN_ISSUED: "API_TOKEN_ISSUED",
  API_TOKEN_REVOKED: "API_TOKEN_REVOKED",
  API_TOKEN_REJECTED: "API_TOKEN_REJECTED",
  MFA_ENROLLMENT_STARTED: "MFA_ENROLLMENT_STARTED",
  MFA_ENABLED: "MFA_ENABLED",
  MFA_DISABLED: "MFA_DISABLED",
  MFA_VERIFICATION_FAILED: "MFA_VERIFICATION_FAILED",
  MFA_CHALLENGE_CREATED: "MFA_CHALLENGE_CREATED",
  MFA_CHALLENGE_VERIFIED: "MFA_CHALLENGE_VERIFIED",
  MFA_CHALLENGE_EXPIRED: "MFA_CHALLENGE_EXPIRED",
  MFA_CHALLENGE_CONSUMED: "MFA_CHALLENGE_CONSUMED",
  SESSION_REVOKED: "SESSION_REVOKED",
  BREAK_GLASS_LOGIN: "BREAK_GLASS_LOGIN",
} as const;

export const MAX_FAILED_LOGIN_ATTEMPTS = 5;

export const LOCKOUT_DURATION_MINUTES = 15;

export const PASSWORD_RESET_TOKEN_BYTES = 32;

export const PASSWORD_RESET_EXPIRATION_MINUTES = 30;

export const CLIENT_SECRET_BYTES = 32;

export const API_ACCESS_TOKEN_BYTES = 32;

export const API_ACCESS_TOKEN_EXPIRATION_MINUTES = 60;

export const API_CLIENT_STATUSES = {
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED",
} as const;

export const API_CLIENT_SCOPES = {
  TICKETS_CREATE: "tickets:create",
  TICKETS_READ: "tickets:read",
  TICKETS_CANCEL: "tickets:cancel",
  DRAWINGS_READ: "drawings:read",
  RESULTS_READ: "results:read",
  WALLETS_DEBIT: "wallets:debit",
  WALLETS_CREDIT: "wallets:credit",
  WALLETS_READ: "wallets:read",
  PLAYERS_READ: "players:read",
  PLAYERS_CREATE: "players:create",
  MARKETS_READ: "markets:read",
  GAMES_READ: "games:read",
} as const;

export const MFA_STATUSES = {
  DISABLED: "DISABLED",
  OPTIONAL: "OPTIONAL",
  REQUIRED: "REQUIRED",
  PENDING_SETUP: "PENDING_SETUP",
  ENABLED: "ENABLED",
} as const;

export const MFA_TOTP_ISSUER = "Lottery Platform";

export const MFA_TOTP_DIGITS = 6;

export const MFA_TOTP_PERIOD_SECONDS = 30;

export const MFA_TOTP_ALGORITHM = "SHA1";

export const MFA_CHALLENGE_TOKEN_BYTES = 32;

export const MFA_CHALLENGE_EXPIRATION_MINUTES = 5;

export const SESSION_STATUSES = {
  ACTIVE: "ACTIVE",
  REVOKED: "REVOKED",
  EXPIRED: "EXPIRED",
} as const;

export const SESSION_HASH_ALGORITHM = "sha256" as const;

export const SESSION_POLICY = {
  defaultDurationSeconds: 60 * 60 * 12,
  operatorDurationSeconds: 60 * 60 * 8,
  playerDurationSeconds: 60 * 60 * 24,
  tokenByteLength: 32,
  hashAlgorithm: SESSION_HASH_ALGORITHM,
  singleActiveSessionIdentityClasses: [IDENTITY_CLASSES.PLATFORM_OPERATOR],
} as const;

export const BREAK_GLASS_STATUSES = {
  ACTIVE: "ACTIVE",
  USED: "USED",
  DISABLED: "DISABLED",
} as const;

export const DEFAULT_PLATFORM_GROUP_NAMES = [
  "Super Admin",
  "Operations Admin",
  "Settlement Admin",
  "Risk Admin",
  "Compliance Admin",
  "Support Admin",
] as const;

export const ARGON2ID_ALGORITHM = "argon2id" as const;

export const ARGON2ID_PASSWORD_SETTINGS = {
  memoryCost: 65536,
  timeCost: 3,
  parallelism: 1,
  hashLength: 32,
} as const;

export const PASSWORD_POLICY = {
  minimumLength: 12,
  requireUppercase: true,
  requireLowercase: true,
  requireNumber: true,
  requireSpecialCharacter: true,
} as const;
